### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by EEAjaegbu** [EEAjaegbu/Stock-Analyzer#1]
**Error**
 This program show error for stock not included in the yahoo finance database or any random input that we searched 

https://stock-risk-return-analyzer.herokuapp.com/

I want to return 404 error when user searched for stocks not included in the yfinance database

**Comment by shyamcody** [comment]
#2 fixes it.

**Comment by EEAjaegbu** [comment]
Thank , Issue resolved.
